### ISSUE TITLE
Problem with VEML6075 

### ISSUE THREAD

**Issue by Wim-tech** [pasgabriele/lora-weather-station#1]
Hi Gabriele,

I am using your lora-weather-station software.

The software is working for me but the VEML6075 is giving me negative results this also outside in full sunlight.
Are you familair with this issue?
I saw several complains about this VEML6075,  i read that a delay of 1000 could solve this problem.

According this example; https://pimylifeup.com/arduino-uv-sensor-veml6075/ ; 
void loop() {
  Serial.print("UV Index reading: "); Serial.println(uv.readUVI());
  delay(1000);
}

I try to add the delay in your software but in return i get several faults after debugging.

I also did a test with a esp8266 and the VEML6075 with the software from "espeasy" the VEML6075 inside home
had a UV index 0 and outside a positive going to 1 (depending sunlight of course), the VEML6075 is working normal.

Looking forward to read your answer.
Kind regards Wim

**Comment by pasgabriele** [comment]
Hi Wim-tech,
are you using my latest version of the sketch? 
I also had negative values for VEML, but i solved it by separating the uv.begin() function from the uv.readUVI(). Now, I use the uv.begin() in the setup function and the uv.read() in the loop. 

In this way I have not anymore negative values.

So essentially, the delay from uv.begin() and uv.readUVI() is necessary.

The sketch is in beta testing, therefore I am changing it day by day. Keep updated.

Let me know if you can solve the VEML problem with this advice.

Thank you!

**Comment by Wim-tech** [comment]
Hi Gabriele,

Thanks for your quick response!

This evening i did a test with your latest test-sketch. (with the weather data reading every 2,8 second)
The VEML values are above zero, and seems to be okay now, i want to test it this weekend outside, i give you more response asap.

Also i changed the resistor for battery measurement to 27K, the voltage reading seems to be good now.

My new question; Is it possible for you to add a light sensor BH1750?
The light sensor can make this weather-station very complete.

Thanks in advance,
Kind regards, Wim

**Comment by pasgabriele** [comment]
For VEML6075: Keep me updated for the VEML measuring so that I can close this topic as solved.

For battery measurement: I advise you to tune the BATTERY_CONV constant using a voltmeter to have more precise battery measurement for your specific microcontroller. Using theoretical calculations, the BATTERY_CONV constant should be = 3,3 / 4095 * 2 = 0,001611721611722, so the Vbatt = analogRaw * 0,001611721611722, but on my case, using the voltometer readings, I had to change the BATTERY_CONV to 0,00173.

For light sensor BH1750: yes, in the PCB there are other 5 unused i2c sockets, therefore you can add the BH1750 or anyother sensors that it communicates via i2c channel and is powered by 3.3V. (for specific ambient light sensor you can also evaluate the VEML7700 or TSL2591).

Regards.

**Comment by Wim-tech** [comment]
Hi Gabriele,

Saterday i did a outside test with the VEML.
It's working but the values are to high, according local weather-forcast the UV index was 7.
The UV level is going up to index of 14, see figure.
The VEML sensor was laying naked in the sun. (no shield).
Please tell me how to adapt the sketch to reduce to a correct UV index.

![VEML6075 uv level 260621](https://user-images.githubusercontent.com/85372522/123549198-332ba100-d768-11eb-9ecc-f69d2cf3ccf1.JPG)

King regards,
Wim

**Comment by pasgabriele** [comment]
No, in my case the UV index is never over 9/10. I tested it as you (no shield). Maybe your sensor is faulty. Do you have a way to try a different one? Anyway, for the UV index, I just use the Adafruit library (https://github.com/adafruit/Adafruit_VEML6075). You can try to investigate your problem in their GitHub. 

Just another information: you reported the WeeWX output. Have you tried to verify raw UV output directly from the serial port?
