### ISSUE TITLE
are there enclosures and so on for 3d printing?

### ISSUE THREAD

**Issue by notecp** [pasgabriele/lora-weather-station#2]
Do you have a enclosure for your components?
if so where may i get them?

**Comment by pasgabriele** [comment]
I did not create personalized enclosures with 3d printer, but in the component list for the external module, I entered the link for the solar shield and declared a geneica junction box. No enclosures are defined for internal component (gateway and weewx server). 

moreover in these days, I am modifying some components of the external module (solar power system and voltage measurements). you will find inconsistencies between the source code (old version) and the description of the external module (more updated). Sorry for the inconvenience.

**Comment by notecp** [comment]
no need to hurry... i am currently in the planning stage :)
